name: Switch Explorer web extension
on:
  push:
    branches: [master]

jobs:
  lint:
    name: Lint Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn run web-ext lint

  build:
    name: Build Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build extension
        run: yarn build

      - name: Upload build as artifact
        uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: SwitchExplorer-ext
          path: web-ext-artifacts/switchexplorer-*.zip
