name: Switch Explorer web extension
on:
  push:
    branches: [master]

jobs:
  lint:
    name: Lint Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn run web-ext lint
